version: '3.8'
services:
  postgresql:
    image: postgres:latest
    container_name: postgresql-elly
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - ./postgresql/data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    restart: "no"
    networks:
      - discord-bot-net

  discord-bot:
    build:
      context: .
    image: discord-bot:latest
    container_name: discord-bot-elly
    ports:
      - "26218:5000"
    environment:
      DISCORD_BOT_TOKEN: ${DISCORD_BOT_TOKEN}
      DATABASE_URL: ${DATABASE_URL}
    volumes:
      - ./config:/app/config
      - ./data:/app/data
    restart: unless-stopped
    networks:
      - discord-bot-net

networks:
  discord-bot-net:
    driver: bridge
