version: '3'
services:
  postgresql:
    image: postgres:latest
    container_name: postgresql-dev
    environment:
      POSTGRES_DB: ${DEV_POSTGRES_DB}
      POSTGRES_USER: ${DEV_POSTGRES_USER}
      POSTGRES_PASSWORD: ${DEV_POSTGRES_PASSWORD}
    volumes:
      - /volume1/docker/postgresql/data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    restart: "no"
    networks:
      - discord-bot-net

  discord-bot-dev:
    image: hhxcusco/discord-bot:dev
    container_name: discord-bot-dev
    ports:
      - "26219:5000"
    environment:
      - DISCORD_BOT_TOKEN=${DEV_DISCORD_BOT_TOKEN}
      - DATABASE_URL=${DEV_DATABASE_URL}
    volumes:
      - /volume1/docker/discord-bot/dev:/app
    restart: "no"
    networks:
      - discord-bot-net

networks:
  discord-bot-net:
    driver: bridge
