name: Build and Push Docker Image for Dev

on:
  push:
    branches:
      - Balthazar

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: hhxcusco/discord-bot:dev

      - name: Deploy
        env:
          DISCORD_BOT_TOKEN: ${{ secrets.DEV_DISCORD_BOT_TOKEN }}
          DATABASE_URL: ${{ secrets.DEV_DATABASE_URL }}
          DEV_POSTGRES_USER: ${{ secrets.DEV_POSTGRES_USER }}
          DEV_POSTGRES_PASSWORD: ${{ secrets.DEV_POSTGRES_PASSWORD }}
          DEV_POSTGRES_DB: ${{ secrets.DEV_POSTGRES_DB }}
        run: docker-compose -f docker-compose.dev.yml up -d
