name: Docker Elly

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: hhxcusco/discord-bot:latest
          cache-from: type=registry,ref=hhxcusco/discord-bot:latest
          cache-to: type=inline

      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      - name: Deploy
        env:
          DISCORD_BOT_TOKEN: ${{ secrets.DISCORD_BOT_TOKEN }}
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          DEV_POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
          DEV_POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
          DEV_POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
        run: docker-compose -f docker-compose.yml up -d
